# Prometheus配置文件
# 用于监控Spec2Test应用和基础设施

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'spec2test-monitor'

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spec2Test应用监控
  - job_name: 'spec2test-app'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL监控（如果启用了postgres_exporter）
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis监控（如果启用了redis_exporter）
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx监控（如果启用了nginx-prometheus-exporter）
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node Exporter监控（系统指标）
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# 告警管理器配置（可选）
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# 远程写入配置（可选，用于长期存储）
# remote_write:
#   - url: "http://remote-storage:8086/api/v1/prom/write?db=prometheus"

# 远程读取配置（可选）
# remote_read:
#   - url: "http://remote-storage:8086/api/v1/prom/read?db=prometheus"
